    plot_regional_gif(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
        OAI_grid.(region{n}).fCO2,parula(20),'fCO2',...
        'Surface {\itf}CO_{2} (\muatm)',OAI_grid.(region{n}).year,...
        OAI_grid.(region{n}).month_of_year,region{n},lme_shape(lme_idx.(region{n})));

    plot_regional_gif(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
            OAI_grid.(region{n}).uTA,cmocean('amp',20),'uTA',...
            'TA Uncertainty (\mumol kg^{-1})',OAI_grid.(region{n}).year,...
            OAI_grid.(region{n}).month_of_year,region{n},lme_shape(lme_idx.(region{n})));

   plot_regional_gif(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
            OAI_grid.(region{n}).TA,cmocean('haline',24),'TA',...
            'Surface {\itA}_{T} (\mumol kg^{-1})',OAI_grid.(region{n}).year,...
            OAI_grid.(region{n}).month_of_year,region{n},lme_shape(lme_idx.(region{n})));
        plot_regional_gif(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
            OAI_grid.(region{n}).pH,flipud(jet(20)),'pH',...
            'Surface pH_{T}',OAI_grid.(region{n}).year,...
            OAI_grid.(region{n}).month_of_year,region{n},lme_shape(lme_idx.(region{n})));
        plot_regional_gif(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
            OAI_grid.(region{n}).OmA,flipud(jet(16)),'OmA',...
            'Surface \Omega_{A}',OAI_grid.(region{n}).year,...
            OAI_grid.(region{n}).month_of_year,region{n},lme_shape(lme_idx.(region{n})));

                plot_regional_gif(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
            OAI_grid.(region{n}).upH,cmocean('amp',20),'upH',...
            'pH Uncertainty',OAI_grid.(region{n}).year,...
            OAI_grid.(region{n}).month_of_year,region{n},lme_shape(lme_idx.(region{n})));

  
        plot_regional_gif(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
            OAI_grid.(region{n}).ufCO2,cmocean('amp',20),'ufCO2',...
            '{\itf}CO_{2} Uncertainty (\muatm)',OAI_grid.(region{n}).year,...
            OAI_grid.(region{n}).month_of_year,region{n},lme_shape(lme_idx.(region{n})));
