
    %% plot estimated fCO2
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).fCO2,...
        parula(20),'fCO2','Surface {\itf}CO_{2} (\muatm)',region{n});

    %% plot estimated pCO2
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).pCO2,...
        parula(20),'pCO2','Surface {\itp}CO_{2} (\muatm)',region{n});
    %% plot estimated TA
%     plot_temporal_mean(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
%         OAI_grid.(region{n}).lon,OAI_grid.(region{n}).TA,...
%         cmocean('haline',24),'TA',...
%         'Surface {\itA}_{T} (\mumol kg^{-1})',region{n});
%     plot_temporal_mean(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
%         OAI_grid.(region{n}).lon,OAI_grid.(region{n}).P,...
%         cmocean('haline',24),'P',...
%         'Surface Phosphate (\mumol kg^{-1})',region{n});
%     plot_temporal_mean(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
%         OAI_grid.(region{n}).lon,OAI_grid.(region{n}).Si,...
%         cmocean('haline',24),'Si',...
%         'Surface Silicate (\mumol kg^{-1})',region{n});

    plot_temporal_mean(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
            OAI_grid.(region{n}).lon,OAI_grid.(region{n}).uTA,...
            cmocean('amp',24),'uTA',...
            'TA Uncertainty (\mumol kg^{-1})',region{n});

        plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).DIC,...
        flipud(jet(20)),'DIC','Dissolved Inorganic Carbon (\mumol kg^{-1})',region{n});
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).pH,...
        flipud(jet(20)),'pH','Surface pH_{T}',region{n});
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).OmA,...
        flipud(jet(16)),'OmA','Surface \Omega_{A}',region{n});
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).OmC,...
        flipud(jet(16)),'OmC','Surface \Omega_{C}',region{n});
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,(10^9).*OAI_grid.(region{n}).H,...
        jet(20),'H','Surface [H^{+}] (nmol kg^{-1})',region{n});
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).CO3,...
        jet(15),'CO3','Surface [CO_{3}^{2-}] (\mumol kg^{-1})',region{n});
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).RF,...
        flipud(jet(28)),'RF','Surface RF',region{n});
    % plot scaled fCO2 uncertainties
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
            OAI_grid.(region{n}).lon,OAI_grid.(region{n}).ufCO2,...
            cmocean('amp',24),'ufCO2',...
            '{\itf}CO_{2} Uncertainty (\muatm)',region{n});
      % plot pH uncertainties
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
            OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
            OAI_grid.(region{n}).lon,OAI_grid.(region{n}).upH,...
            cmocean('amp',20),'upH',...
            'pH Uncertainty',region{n});

        plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).uTA,...
        flipud(jet(28)),'uTA','Surface TA Uncertainty (\mumol kg^{-1})',region{n});
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).upH,...
        flipud(jet(28)),'upH','Surface pH Uncertainty',region{n});