% Load Variables
% 
% This script loads satellite and reanalysis variables for five US large
% Marine Ecosystems (Alaska, California Current, Insular Pacific / Hawaii,
% Gulf of Mexico / Caribbean, and US East Coast) and regrids them in
% preparation for clustering and machine learning algorithm fits.
% 
% Written by J.D. Sharp: 8/19/22
% Last updated by J.D. Sharp: 8/30/22
% 

% define regions of interest
region = {'CCS' 'AK' 'EastCoast' 'GoM_Car' 'Hawaii'};

% define path
path = pwd;

for n = 1:length(region)

    %% load gridded pCO2
    load(['Data/' region{n} '/gridded_pco2'],'SOCAT_grid');

    %% display status
    disp(['Loading predictor variables (' region{n} ')']);

    %% Duplicate SOCAT grid for predictors grid
    Preds_grid.(region{n}).lon = SOCAT_grid.(region{n}).lon;
    Preds_grid.(region{n}).lat = SOCAT_grid.(region{n}).lat;
    Preds_grid.(region{n}).lim = SOCAT_grid.(region{n}).lim;
    Preds_grid.(region{n}).dim = SOCAT_grid.(region{n}).dim;
    Preds_grid.(region{n}).month = SOCAT_grid.(region{n}).month;
    Preds_grid.(region{n}).year = SOCAT_grid.(region{n}).year;
    Preds_grid.(region{n}).month_of_year = SOCAT_grid.(region{n}).month_of_year;

    %% Determine ocean mask
    lon_tmp = repmat(Preds_grid.(region{n}).lon,1,Preds_grid.(region{n}).dim.y);
    lon_tmp(lon_tmp > 180) = lon_tmp(lon_tmp > 180) - 360;
    lat_tmp = repmat(Preds_grid.(region{n}).lat',Preds_grid.(region{n}).dim.x,1);
    Preds_grid.(region{n}).ocean_mask = ~landmask(lat_tmp,lon_tmp);
    clear lat_tmp lon_tmp

    %% Calculate distance from coast
    Preds_grid.(region{n}).Dist = ...
        dist2coast(repmat(Preds_grid.(region{n}).lat',Preds_grid.(region{n}).dim.x,1),...
        repmat(Preds_grid.(region{n}).lon,1,Preds_grid.(region{n}).dim.y));

    %% Obtain sea surface salinity from ECCO reanalysis
    Preds_grid.(region{n}).SSS = ...
        import_SSS_ECCO(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).ocean_mask,path);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SSS,...
        29.75,38.25,17,'SSS','Sea Surface Salinity',region{n});

    %% Obtain sea surface height from ECCO reanalysis
    Preds_grid.(region{n}).SSH = ...
        import_SSH_ECCO(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).ocean_mask,path);

    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SSH,...
        -0.05,1.05,11,'SSH','Sea Surface Height',region{n});

    %% Obtain sea surface temperature from OISSTv2
    Preds_grid.(region{n}).SST = ...
        import_SST_OISST(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).ocean_mask,path);

    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SST,...
        1,31,15,'SST','Sea Surface Temperature',region{n});

    %% Obtain sea surface chlorophyll from satellite measurements
    Preds_grid.(region{n}).CHL = ...
        import_CHL_NASA(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).ocean_mask,path);
    Preds_grid.(region{n}).CHL(Preds_grid.(region{n}).CHL< 0) = 0.0001;

    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).CHL,...
        -0.025,1.025,21,'CHL','Sea Surface Chlorophyll (log_{10})',region{n});

    %% Obtain wind speed from ERA5 re-analysis
    Preds_grid.(region{n}).WindSpeed = ...
        import_Winds_ERA5(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).ocean_mask,path);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).WindSpeed,...
        -0.5,12.5,13,'WindSpeed','Wind Speed (m s^{-1})',region{n});

    %% Obtain bathymetry from ETOPO2
    Preds_grid.(region{n}).Bathy = ...
        import_Bathy_ETOPO2(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).ocean_mask,path);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).Bathy,...
        -125,6125,25,'Bathymetry','Bottom Depth (m)',region{n});

    %% Obtain mixed layer depth from HYCOM model
    Preds_grid.(region{n}).MLD = ...
        import_MLD_HYCOM(Preds_grid.(region{n}).lat,...
                         Preds_grid.(region{n}).lon,...
                         Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).ocean_mask,path);
    Preds_grid.(region{n}).MLD(Preds_grid.(region{n}).MLD<0) = 10;
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).MLD,...
        -5,205,21,'MLD','Mixed Layer Depth (m)',region{n});

    %% Obtain atmospheric pressure from NCEP
    Preds_grid.(region{n}).mslp = ...
        import_mslp_NCEP(Preds_grid.(region{n}).lat,...
                         Preds_grid.(region{n}).lon,...
                         Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).ocean_mask,path);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).mslp,...
        0.9775,1.0325,21,'mslp','Sea Level Pressure (Atmospheres)',region{n});

    %% Obtain atmospheric pCO2 from NOAA MBL product
    Preds_grid.(region{n}).pCO2_atm = ...
        import_pCO2_MBL(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).SSS,...
                        Preds_grid.(region{n}).SST,...
                        Preds_grid.(region{n}).mslp,path);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).pCO2_atm,...
        369.5,390.5,21,'pCO2_atm','Atmospheric pCO_{2} (\muatm)',region{n});

    % Save gridded predictor data
    save(['Data/' region{n} '/gridded_predictors'],'Preds_grid','-v7.3');
    clearvars -except region path

end
