% Load Variables
% 
% This script loads satellite and reanalysis variables for five US large
% Marine Ecosystems (Alaska, California Current, Insular Pacific / Hawaii,
% Gulf of Mexico / Caribbean, and US East Coast) and regrids them in
% preparation for clustering and machine learning algorithm fits.
% 
% Written by J.D. Sharp: 8/19/22
% Last updated by J.D. Sharp: 11/30/22
% 

%% define path
filepath = pwd;

%% load predictor variables for each LME
for n = 1:length(region)

    %% load gridded pCO2
    load(['Data/' region{n} '/gridded_pco2'],'SOCAT_grid');

    %% display status
    disp(['Loading predictor variables (' region{n} ')']);

    %% Duplicate SOCAT grid for predictors grid
    Preds_grid.(region{n}).lon = SOCAT_grid.(region{n}).lon;
    Preds_grid.(region{n}).lat = SOCAT_grid.(region{n}).lat;
    Preds_grid.(region{n}).lim = SOCAT_grid.(region{n}).lim;
    Preds_grid.(region{n}).dim = SOCAT_grid.(region{n}).dim;
    Preds_grid.(region{n}).month = SOCAT_grid.(region{n}).month;
    Preds_grid.(region{n}).year = SOCAT_grid.(region{n}).year;
    Preds_grid.(region{n}).month_of_year = SOCAT_grid.(region{n}).month_of_year;
    Preds_grid.(region{n}).idxspc = SOCAT_grid.(region{n}).idxspc;

    %% Calculate distance from coast
    Preds_grid.(region{n}).Dist = ...
        dist2coast(repmat(Preds_grid.(region{n}).lat',Preds_grid.(region{n}).dim.x,1),...
        repmat(Preds_grid.(region{n}).lon,1,Preds_grid.(region{n}).dim.y));

    %% Obtain sea surface salinity from GLORYS
    Preds_grid.(region{n}).SSS = ...
        import_SSS_GLORYS(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SSS,...
        cmocean('haline',20),'SSS','Sea Surface Salinity',region{n});

    %% Obtain sea surface height from CMEMS satellite product

    % exclude Bering-Chukchi and Beaufort Seas
    if n == 5 || n == 6
        Preds_grid.(region{n}).SSH = ...
            nan(size(Preds_grid.(region{n}).idxspc));
    else
        Preds_grid.(region{n}).SSH = ...
            import_SSH_CMEMS(Preds_grid.(region{n}).lat,...
                            Preds_grid.(region{n}).lon,...
                            Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    end

    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SSH,...
        parula(20),'SSH','Sea Surface Height Anomaly (m)',region{n});

    %% Obtain sea surface temperature from OISSTv2
    Preds_grid.(region{n}).SST = ...
        import_SST_OISST(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);

    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SST,...
        cmocean('thermal',20),'SST',['Sea Surface Temperature (' char(176) 'C)'],region{n});

    %% Obtain sea surface ice concentration from OISSTv2
    Preds_grid.(region{n}).IceC = ...
        import_Ice_OISST(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);

    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).IceC,...
        cmocean('tempo',20),'IceC','Sea Ice Concentration Fraction',region{n});

    %% Obtain sea surface chlorophyll from satellite measurements

    % exclude Bering-Chukchi and Beaufort Seas
    if n == 5 || n == 6
        Preds_grid.(region{n}).CHL = nan(size(Preds_grid.(region{n}).idxspc));
    else
        Preds_grid.(region{n}).CHL = ...
            import_CHL_NASA(Preds_grid.(region{n}).lat,...
                            Preds_grid.(region{n}).lon,...
                            Preds_grid.(region{n}).month,...
                            Preds_grid.(region{n}).idxspc(:,:,1),filepath);
        Preds_grid.(region{n}).CHL(Preds_grid.(region{n}).CHL<0) = 0.0001;
    end
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).CHL,...
        cmocean('algae',20),'CHL','Sea Surface Chlorophyll (log_{10})',region{n});

    %% Obtain wind speed from ERA5 re-analysis
    Preds_grid.(region{n}).WindSpeed = ...
        import_Winds_ERA5(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).WindSpeed,...
        cmocean('amp',20),'WindSpeed','Wind Speed (m s^{-1})',region{n});

    %% Obtain bathymetry from ETOPO2
    Preds_grid.(region{n}).Bathy = ...
        import_Bathy_ETOPO2(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    % negative trap for bathymetry
    Preds_grid.(region{n}).Bathy(Preds_grid.(region{n}).Bathy < 0) = 0;
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).Bathy,...
        cmocean('deep',20),'Bathymetry','Bottom Depth (m)',region{n});

    %% Obtain mixed layer depth
    Preds_grid.(region{n}).MLD = ...
        import_MLD_GLORYS(Preds_grid.(region{n}).lat,...
                         Preds_grid.(region{n}).lon,...
                         Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    Preds_grid.(region{n}).MLD(Preds_grid.(region{n}).MLD<0) = 10;
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).MLD,...
        jet(20),'MLD_glorys','Mixed Layer Depth (m)',region{n});

    %% Obtain atmospheric pressure from NCEP
    Preds_grid.(region{n}).mslp = ...
        import_mslp_NCEP(Preds_grid.(region{n}).lat,...
                         Preds_grid.(region{n}).lon,...
                         Preds_grid.(region{n}).month,...
                         Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).mslp,...
        cmocean('dense',20),'mslp','Sea Level Pressure (atm)',region{n});

    %% Obtain atmospheric pCO2 from NOAA MBL product
    Preds_grid.(region{n}).pCO2_atm = ...
        import_pCO2_MBL(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).SSS,...
                        Preds_grid.(region{n}).SST,...
                        Preds_grid.(region{n}).mslp,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    
    % test plot
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).pCO2_atm,...
        cmocean('solar',20),'pCO2_atm','Atmospheric pCO_{2} (\muatm)',region{n});

    %% Save gridded predictor data
    save(['Data/' region{n} '/gridded_predictors'],'Preds_grid','-v7.3');

    % clean up
    clear Preds_grid SOCAT_grid

end

% clean up
clear filepath

%% plot surface variables across full region
plot_temporal_mean_full(29.75,38.25,0.5,cmocean('haline',17),'SSS','Sea Surface Salinity',region,lme_shape,lme_idx)
plot_temporal_mean_full(-0.015,0.105,0.01,parula(12),'SSH','Sea Surface Height Anomaly (m)',region,lme_shape,lme_idx)
plot_temporal_mean_full(1,31,2,cmocean('thermal',15),'SST',['Sea Surface Temperature (' char(176) 'C)'],region,lme_shape,lme_idx)
plot_temporal_mean_full(-0.025,1.025,0.05,cmocean('tempo',21),'IceC','Sea Ice Concentration Fraction',region,lme_shape,lme_idx)
plot_temporal_mean_full(-0.025,1.025,0.05,cmocean('algae',21),'CHL','Sea Surface Chlorophyll (log_{10})',region,lme_shape,lme_idx)
plot_temporal_mean_full(-0.5,12.5,1,cmocean('amp',13),'WindSpeed','Wind Speed (m s^{-1})',region,lme_shape,lme_idx)
plot_temporal_mean_full(-125,6125,250,cmocean('deep',25),'Bathy','Bottom Depth (m)',region,lme_shape,lme_idx)
plot_temporal_mean_full(-2.5,52.5,5,jet(11),'MLD','Mixed Layer Depth (m)',region,lme_shape,lme_idx)
plot_temporal_mean_full(0.990,1.010,0.001,cmocean('dense',21),'mslp','Sea Level Pressure (atm)',region,lme_shape,lme_idx)
plot_temporal_mean_full(369.5,390.5,1,cmocean('solar',21),'pCO2_atm','Atmospheric pCO_{2} (\muatm)',region,lme_shape,lme_idx)

%% plot gifs of surface variables across full region
plot_full_gif(29.75,38.25,cmocean('haline',17),'SSS','Sea Surface Salinity',region,lme_shape,lme_idx)
plot_full_gif(-0.015,0.105,parula(12),'SSH','Sea Surface Height Anomaly (m)',region,lme_shape,lme_idx)
plot_full_gif(1,31,cmocean('thermal',15),'SST',['Sea Surface Temperature (' char(176) 'C)'],region,lme_shape,lme_idx)
plot_full_gif(-0.025,1.025,cmocean('tempo',21),'IceC','Sea Ice Concentration Fraction',region,lme_shape,lme_idx)
plot_full_gif(-0.025,1.025,cmocean('algae',21),'CHL','Sea Surface Chlorophyll (log_{10})',region,lme_shape,lme_idx)
plot_full_gif(-0.5,12.5,cmocean('amp',13),'WindSpeed','Wind Speed (m s^{-1})',region,lme_shape,lme_idx)
plot_full_gif(-2.5,52.5,jet(11),'MLD','Mixed Layer Depth (m)',region,lme_shape,lme_idx)
plot_full_gif(0.990,1.010,cmocean('dense',21),'mslp','Sea Level Pressure (atm)',region,lme_shape,lme_idx)
plot_full_gif(369.5,390.5,cmocean('solar',21),'pCO2_atm','Atmospheric pCO_{2} (\muatm)',region,lme_shape,lme_idx)
