% Load Variables
% 
% This script loads satellite and reanalysis variables for five US large
% Marine Ecosystems (Alaska, California Current, Insular Pacific / Hawaii,
% Gulf of Mexico / Caribbean, and US East Coast) and regrids them in
% preparation for clustering and machine learning algorithm fits.
% 
% Written by J.D. Sharp: 8/19/22
% Last updated by J.D. Sharp: 11/30/22
% 

%% define path
filepath = pwd;

%% load predictor variables for each LME
for n = 1:length(region)

    %% load gridded pCO2
    load(['Data/' region{n} '/gridded_pco2'],'SOCAT_grid');

    %% display status
    disp(['Loading predictor variables (' region{n} ')']);

    %% Duplicate SOCAT grid for predictors grid
    Preds_grid.(region{n}).lon = SOCAT_grid.(region{n}).lon;
    Preds_grid.(region{n}).lat = SOCAT_grid.(region{n}).lat;
    Preds_grid.(region{n}).lim = SOCAT_grid.(region{n}).lim;
    Preds_grid.(region{n}).dim = SOCAT_grid.(region{n}).dim;
    Preds_grid.(region{n}).month = SOCAT_grid.(region{n}).month;
    Preds_grid.(region{n}).year = SOCAT_grid.(region{n}).year;
    Preds_grid.(region{n}).month_of_year = SOCAT_grid.(region{n}).month_of_year;
    Preds_grid.(region{n}).idxspc = SOCAT_grid.(region{n}).idxspc;

    %% Calculate distance from coast
    Preds_grid.(region{n}).Dist = ...
        dist2coast(repmat(Preds_grid.(region{n}).lat',Preds_grid.(region{n}).dim.x,1),...
        repmat(Preds_grid.(region{n}).lon,1,Preds_grid.(region{n}).dim.y));

    %% Obtain sea surface salinity from GLORYS
    Preds_grid.(region{n}).SSS = ...
        import_SSS_GLORYS(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);

    %% Obtain sea surface height from CMEMS satellite product
    if n == 5 || n == 6
        % exclude Bering-Chukchi and Beaufort Seas
        Preds_grid.(region{n}).SSH = ...
            nan(size(Preds_grid.(region{n}).idxspc));
    else
        Preds_grid.(region{n}).SSH = ...
            import_SSH_CMEMS(Preds_grid.(region{n}).lat,...
                            Preds_grid.(region{n}).lon,...
                            Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    end

    %% Obtain sea surface temperature from OISSTv2
    Preds_grid.(region{n}).SST = ...
        import_SST_OISST(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);

    %% Obtain sea surface ice concentration from OISSTv2
    Preds_grid.(region{n}).IceC = ...
        import_Ice_OISST(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);

    %% Obtain sea surface chlorophyll from satellite measurements
    if n == 5 || n == 6
        % exclude Bering-Chukchi and Beaufort Seas
        Preds_grid.(region{n}).CHL = nan(size(Preds_grid.(region{n}).idxspc));
    else
        Preds_grid.(region{n}).CHL = ...
            import_CHL_NASA(Preds_grid.(region{n}).lat,...
                            Preds_grid.(region{n}).lon,...
                            Preds_grid.(region{n}).month,...
                            Preds_grid.(region{n}).idxspc(:,:,1),filepath);
        Preds_grid.(region{n}).CHL(Preds_grid.(region{n}).CHL<0) = 0.0001;
    end
    
    %% Obtain wind speed from ERA5 re-analysis
    Preds_grid.(region{n}).WindSpeed = ...
        import_Winds_ERA5(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    
    %% Obtain bathymetry from ETOPO2
    Preds_grid.(region{n}).Bathy = ...
        import_Bathy_ETOPO2(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    % negative trap for bathymetry
    Preds_grid.(region{n}).Bathy(Preds_grid.(region{n}).Bathy < 0) = 0;

    %% Obtain mixed layer depth
    Preds_grid.(region{n}).MLD = ...
        import_MLD_GLORYS(Preds_grid.(region{n}).lat,...
                         Preds_grid.(region{n}).lon,...
                         Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);
    Preds_grid.(region{n}).MLD(Preds_grid.(region{n}).MLD<0) = 10;
    
    %% Obtain atmospheric pressure from NCEP
    Preds_grid.(region{n}).mslp = ...
        import_mslp_NCEP(Preds_grid.(region{n}).lat,...
                         Preds_grid.(region{n}).lon,...
                         Preds_grid.(region{n}).month,...
                         Preds_grid.(region{n}).idxspc(:,:,1),filepath);

    %% Obtain atmospheric pCO2 from NOAA MBL product
    Preds_grid.(region{n}).pCO2_atm = ...
        import_pCO2_MBL(Preds_grid.(region{n}).lat,...
                        Preds_grid.(region{n}).lon,...
                        Preds_grid.(region{n}).month,...
                        Preds_grid.(region{n}).SSS,...
                        Preds_grid.(region{n}).SST,...
                        Preds_grid.(region{n}).mslp,...
                        Preds_grid.(region{n}).idxspc(:,:,1),filepath);

    %% Save gridded predictor data
    save(['Data/' region{n} '/gridded_predictors'],'Preds_grid','-v7.3');

    % clean up
    clear Preds_grid SOCAT_grid

end

% clean up
clear
