% Plot regional predictor variables

% this script defines the bounds of the eleven LMEs
define_regions_eiwg

for n = 1:length(region)
    % load data
    load(['Data/' region{n} '/gridded_predictors'],'Preds_grid');
    % Salinity
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SSS,...
        cmocean('haline',20),'SSS','Sea Surface Salinity',region{n},lme_shape,lme_idx);
    % SSH
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SSH,...
        parula(20),'SSH','Sea Surface Height Anomaly (m)',region{n},lme_shape,lme_idx);
    % SST
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SST,...
        cmocean('thermal',20),'SST',['Sea Surface Temperature (' char(176) 'C)'],region{n},lme_shape,lme_idx);
    % Sea Ice
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).IceC,...
        cmocean('tempo',20),'IceC','Sea Ice Concentration Fraction',region{n},lme_shape,lme_idx);
    % Chlorophyll
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).CHL,...
        cmocean('algae',20),'CHL','Sea Surface Chlorophyll (log_{10})',region{n},lme_shape,lme_idx);
    % Wind Speed
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).WindSpeed,...
        cmocean('amp',20),'WindSpeed','Wind Speed (m s^{-1})',region{n},lme_shape,lme_idx);
    % Bathymetry
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).Bathy,...
        cmocean('deep',20),'Bathymetry','Bottom Depth (m)',region{n},lme_shape,lme_idx);
    % MLD
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).MLD,...
        jet(20),'MLD_glorys','Mixed Layer Depth (m)',region{n},lme_shape,lme_idx);
    % Sea Level Pressure
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).mslp,...
        cmocean('dense',20),'mslp','Sea Level Pressure (atm)',region{n},lme_shape,lme_idx);
    % pCO2 atm
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).pCO2_atm,...
        cmocean('solar',20),'pCO2_atm','Atmospheric pCO_{2} (\muatm)',region{n},lme_shape,lme_idx);
end

% clean up
clear