% plot predictor variability for each region

% this script defines the bounds of the eighteen LMEs
define_regions_eiwg

for n = 1%:length(region)
    % load data
    load(['Data/' region{n} '/gridded_predictors'],'Preds_grid');
    % create plots
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SSS_var,...
        cmocean('haline',20),'SSS_var','Sea Surface Salinity Var.',region{n});
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).mslp_var,...
        cmocean('dense',20),'mslp_var','Sea Level Pressure Var.',region{n});
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SST_var,...
        cmocean('thermal',20),'SST_var','Sea Surface Temperature Var.',region{n});
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).CHL_var,...
        cmocean('algae',20),'CHL_var','Chlorophyll Var.',region{n});
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).WindSpeed_var,...
        cmocean('amp',20),'WindSpeed_var','Wind Speed Var.',region{n});
    plot_temporal_mean(Preds_grid.(region{n}).lim,...
        Preds_grid.(region{n}).dim,Preds_grid.(region{n}).lat,...
        Preds_grid.(region{n}).lon,Preds_grid.(region{n}).SSH_var,...
        parula(20),'SSH_var','Sea Level Anomaly Var.',region{n});

end
