%% create regional animations of RFR-LME indicators
addpath(genpath(pwd));
% this script defines the bounds of the eleven LMEs
define_regions_eiwg

for n = 8%1:length(region)

    % load gridded fCO2, predictors, and models
    load(['Data/' region{n} '/ML_fCO2'],'OAI_grid');

    % plot estimated fCO2
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).fCO2,...
        flipud(slanCM('romao')),'fCO2','Surface {\itf}CO_{2} (\muatm)',...
        region{n},lme_shape,lme_idx);

    % plot estimated pCO2
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).pCO2,...
        flipud(slanCM('romao')),'pCO2','Surface {\itp}CO_{2} (\muatm)',...
        region{n},lme_shape,lme_idx);

    % plot estimated TA
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).TA,...
        flipud(slanCM('romao')),'TA',...
        'Surface {\itA}_{T} (\mumol kg^{-1})',...
        region{n},lme_shape,lme_idx);

    % plot estimated phosphate
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).P,...
        flipud(slanCM('romao')),'P',...
        'Surface Phosphate (\mumol kg^{-1})',...
        region{n},lme_shape,lme_idx);

    % plot estimated silicate
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).Si,...
        flipud(slanCM('romao')),'Si',...
        'Surface Silicate (\mumol kg^{-1})',...
        region{n},lme_shape,lme_idx);

    % plot estimated TA uncertainty
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).uTA,...
        cmocean('amp'),'uTA',...
        'TA Uncertainty (\mumol kg^{-1})',...
        region{n},lme_shape,lme_idx);

    % plot estimated DIC
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).DIC,...
        flipud(slanCM('romao')),'DIC','Dissolved Inorganic Carbon (\mumol kg^{-1})',...
        region{n},lme_shape,lme_idx);
    
    % plot estimated pH
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).pH,...
        flipud(slanCM('romao')),'pH','Surface pH_{T}',...
        region{n},lme_shape,lme_idx);

    % plot estimated Omega A
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).OmA,...
        flipud(slanCM('romao')),'OmA','Surface \Omega_{A}',...
        region{n},lme_shape,lme_idx);

    % plot estimated Omega C
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).OmC,...
        flipud(slanCM('romao')),'OmC','Surface \Omega_{C}',...
        region{n},lme_shape,lme_idx);

    % plot estimated [H+]
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,(10^9).*OAI_grid.(region{n}).H,...
        flipud(slanCM('romao')),'H','Surface [H^{+}] (nmol kg^{-1})',...
        region{n},lme_shape,lme_idx);

    % plot estimated CO3
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).CO3,...
        flipud(slanCM('romao')),'CO3','Surface [CO_{3}^{2-}] (\mumol kg^{-1})',...
        region{n},lme_shape,lme_idx);

    % plot estimated RF
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).RF,...
        flipud(slanCM('romao')),'RF','Surface RF',...
        region{n},lme_shape,lme_idx);

    % plot scaled fCO2 uncertainties
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).ufCO2,...
        cmocean('amp'),'ufCO2',...
        '{\itf}CO_{2} Uncertainty (\muatm)',...
        region{n},lme_shape,lme_idx);

    % plot pH uncertainties
    plot_temporal_mean(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).dim,OAI_grid.(region{n}).lat,...
        OAI_grid.(region{n}).lon,OAI_grid.(region{n}).upH,...
        cmocean('amp'),'upH','pH Uncertainty',...
        region{n},lme_shape,lme_idx);



end
