%% create regional animations of RFR-LME indicators
addpath(genpath(pwd));
% this script defines the bounds of the eleven LMEs
define_regions_eiwg

for n = 2%:length(region)

    % load gridded fCO2, predictors, and models
    load(['Data/' region{n} '/ML_fCO2'],'OAI_grid');

% plot_regional_gif(OAI_grid.(region{n}).lim,...
%     OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%     OAI_grid.(region{n}).fCO2,flipud(slanCM('romao')),'fCO2',...
%     'Surface {\itf}CO_{2} (\muatm)',OAI_grid.(region{n}).year,...
%     OAI_grid.(region{n}).month_of_year,region{n},...
%     lme_shape(lme_idx.(region{n})));
% 
% plot_regional_gif(OAI_grid.(region{n}).lim,...
%     OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%     OAI_grid.(region{n}).pCO2,flipud(slanCM('romao')),'fCO2',...
%     'Surface {\itp}CO_{2} (\muatm)',OAI_grid.(region{n}).year,...
%     OAI_grid.(region{n}).month_of_year,region{n},...
%     lme_shape(lme_idx.(region{n})));
% 
% plot_regional_gif(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%         OAI_grid.(region{n}).uTA,cmocean('amp'),'uTA',...
%         'TA Uncertainty (\mumol kg^{-1})',OAI_grid.(region{n}).year,...
%         OAI_grid.(region{n}).month_of_year,region{n},...
%         lme_shape(lme_idx.(region{n})));
% 
% plot_regional_gif(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%         OAI_grid.(region{n}).TA,flipud(slanCM('romao')),'TA',...
%         'Surface {\itA}_{T} (\mumol kg^{-1})',OAI_grid.(region{n}).year,...
%         OAI_grid.(region{n}).month_of_year,region{n},...
%         lme_shape(lme_idx.(region{n})));
% 
%     plot_regional_gif(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%         OAI_grid.(region{n}).pH,flipud(slanCM('romao')),'pH',...
%         'Surface pH_{T}',OAI_grid.(region{n}).year,...
%         OAI_grid.(region{n}).month_of_year,region{n},...
%         lme_shape(lme_idx.(region{n})));

    plot_regional_gif(OAI_grid.(region{n}).lim,...
        OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
        OAI_grid.(region{n}).OmA,flipud(slanCM('romao')),'OmA',...
        'Surface \Omega_{A}',OAI_grid.(region{n}).year,...
        OAI_grid.(region{n}).month_of_year,region{n},...
        lme_shape(lme_idx.(region{n})));
% 
%     plot_regional_gif(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%         OAI_grid.(region{n}).upH,cmocean('amp'),'upH',...
%         'pH Uncertainty',OAI_grid.(region{n}).year,...
%         OAI_grid.(region{n}).month_of_year,region{n},...
%         lme_shape(lme_idx.(region{n})));
% 
%     plot_regional_gif(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%         OAI_grid.(region{n}).ufCO2,cmocean('amp'),'ufCO2',...
%         '{\itf}CO_{2} Uncertainty (\muatm)',OAI_grid.(region{n}).year,...
%         OAI_grid.(region{n}).month_of_year,region{n},...
%         lme_shape(lme_idx.(region{n})));

%     plot_regional_gif(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%         OAI_grid.(region{n}).DIC,flipud(slanCM('romao')),'DIC',...
%         'Surface {\it}C_{T} (\mumol kg^{-1})',OAI_grid.(region{n}).year,...
%         OAI_grid.(region{n}).month_of_year,region{n},...
%         lme_shape(lme_idx.(region{n})));
% 
%     plot_regional_gif(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%         OAI_grid.(region{n}).OmC,flipud(slanCM('romao')),'OmC',...
%         'Surface \Omega_{C}',OAI_grid.(region{n}).year,...
%         OAI_grid.(region{n}).month_of_year,region{n},...
%         lme_shape(lme_idx.(region{n})));
% 
%     plot_regional_gif(OAI_grid.(region{n}).lim,...
%         OAI_grid.(region{n}).lat,OAI_grid.(region{n}).lon,...
%         OAI_grid.(region{n}).CO3,flipud(slanCM('romao')),'CO3',...
%         '[CO_{3}^{2-}] (\mumol kg^{-1})',OAI_grid.(region{n}).year,...
%         OAI_grid.(region{n}).month_of_year,region{n},...
%         lme_shape(lme_idx.(region{n})));

end