% this script defines the bounds of the eleven LMEs
define_regions_eiwg

for n = 7%1:length(region)
    % load data
    load(['Data/' region{n} '/gridded_pco2'],'SOCAT_grid');
    % for each LME, plot an amimation of available fCO2 observations
    plot_regional_gif(SOCAT_grid.(region{n}).lim,...
        SOCAT_grid.(region{n}).lat,SOCAT_grid.(region{n}).lon,...
        SOCAT_grid.(region{n}).fco2_ave_wtd_detrend,flipud(slanCM('romao')),'fCO2_obs',...
        'Surface {\itf}CO_{2} (\muatm)',SOCAT_grid.(region{n}).year,...
        SOCAT_grid.(region{n}).month_of_year,region{n},lme_shape(lme_idx.(region{n})));
end